# Rolling nightly channel pointer — auto-generated by .github/workflows/nightly.yml.
#
# This file lives on the `nightly` git ref. The hashes and version below
# match the artifacts published in the current rolling nightly release.
# This file is NOT present on `main` with real hashes — always consume via
# the `nightly` ref:
#
#   nix run github:0xErwin1/dbflux/nightly#dbflux-nightly
#
# From-source nightly (no hash needed):
#
#   nix run github:0xErwin1/dbflux/nightly#dbflux-source
{
  version = "0.8.0-nightly+74bf007";

  artifacts = {
    "x86_64-linux" = {
      url = "https://github.com/0xErwin1/dbflux/releases/download/nightly/dbflux-linux-amd64.tar.gz";
      hash = "sha256-AHDeUmwe+1vtN281tbhgkv1xJ+VS9buKUq8vBxeSXYk=";
    };
    "aarch64-linux" = {
      url = "https://github.com/0xErwin1/dbflux/releases/download/nightly/dbflux-linux-arm64.tar.gz";
      hash = "sha256-0BewNVrESVFlumQsjJYzvk1u0EnLF87xlFE0PX+wDPM=";
    };
  };
}
